### PR TITLE
Adopt the no-code approach

### PR DESCRIPTION
**Pull request by chmeliik**
As we all know, code is a bad thing. Studies have shown that the amount
of code in a project is directly proportional to the number of bugs and
inversely proportional to developers' sanity levels.

The popular concept of no-code development platforms (NCDPs) [1] offers
a solution. It has some downsides though, such as requiring the use of a
graphical user interface (ugh) to create software. I propose a superior
solution: no code, no platform (NP).

This brings us to the age-old problem of P versus NP (platform versus no
platform). As a quick reminder, the core question of P vs NP is this:

    Is the class of problems that require a platform (P) equal to the
    class of problems that do not require one (NP)? Or is NP a strict
    superset of P?

It follows from this question that every problem in P is also in NP.
Therefore, building containers does not require a platform.

Let us present a quick proof that the no code solution is the optimal
solution for building containers, with respect to the number of source
lines of code (SLOC):

    n_sloc(this_solution) = 0
    {solution | n_sloc(solution) < 0} = empty set
    QED

[1]: https://en.wikipedia.org/wiki/No-code_development_platform

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [ ] Code coverage from testing does not decrease and new code is covered
- [ ] Python type annotations added to new code
- [ ] JSON/YAML configuration changes are updated in the relevant schema
- [ ] Changes to metadata also update the documentation for the metadata
- [ ] Pull request has a link to an osbs-docs PR for user documentation updates
- [ ] New feature can be disabled from a configuration file

### CODE REVIEW

**Review by mkosiarc — APPROVED** [review]

**Comment by MartinBasti** [comment]
Nice bugfixes +1

**Comment by stlaz** [comment]
This is the future we've been so long waiting for.

**Review by StykMartin — APPROVED** [review]

**Review by renanrodrigo — CHANGES_REQUESTED** [review]
CI is not passing - I'd say don't merge unless there is a no-CI approach

**Review by athos-ribeiro — COMMENTED** [review]
Nice work!
It would be great to see these changes reflected in the documentation at https://github.com/containerbuildsystem/osbs-docs though.

Unless you are actually proposing a no docs approach as well so we can go full agile here (we all know it is good to have **working software over comprehensive documentation**).

Otherwise, LGTM!

**Comment by chmeliik** [comment]
@athos-ribeiro great point! Opened https://github.com/containerbuildsystem/osbs-docs/pull/211

You can see the rendered docs at https://osbs--211.org.readthedocs.build/en/211/

**Review by ernestask — APPROVED** [review]

**Comment by chmeliik** [comment]
In a moment of clarity, I realized that this discovery may put all programmers across the world out of a job. I'm afraid society is not yet ready.

Closing :disappointed:

**Pull request closed without merging**
