### PR TITLE
Build task stub

### PR DESCRIPTION
**Pull request by chmeliik**
CLOUDBLD-8657

Implement the build task stub. It doesn't do anything useful, but the path from here to a functional build task should be relatively short. More info in the individual commits.

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [x] Python type annotations added to new code
- [n/a] JSON/YAML configuration changes are updated in the relevant schema
- [n/a] Changes to metadata also update the documentation for the metadata
- [n/a] Pull request has a link to an osbs-docs PR for user documentation updates
- [n/a] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by chmeliik** [comment]
To try this out locally:

<details>
<summary>prepare files</summary>

`/tmp/user_params.json`
```json
{"user":"acmiel","build_json_dir":"this is not used","git_ref":"idk","git_uri":"idk","image_tag":"container-registry.example.com/osbs/spam:v1.0"}
```

`/tmp/config.yaml`
```yaml
version: 1

koji:
    hub_url: https://koji.example.com/hub
    root_url: https://koji.example.com/root
    auth:
        ssl_certs_dir: /var/run/secrets/atomic-reactor/kojisecret
    use_fast_upload: false

openshift:
    url: https://openshift.example.com
    auth:
        enable: True
    build_json_dir: /usr/share/osbs/

# Output registries (built images are pushed here)
registries:
- url: https://container-registry.example.com/v2
  auth:
    cfg_path: /var/run/secrets/atomic-reactor/v2-registry-dockercfg

# Default source registry (base images are pulled from here)
source_registry:
    url: https://registry.private.example.com
```

`/tmp/build/x86_64/Dockerfile`
```dockerfile
FROM scratch
```

`/tmp/context/workflow.json`
```json
{"dockerfile_images":{"original_parents":[],"local_parents":[],"source_registry":null,"organization":null,"__type__":"DockerfileImages"},"tag_conf":{"primary_images":[],"unique_images":[{"str":"container-registry.example.com/osbs/foo:v1.0","__type__":"ImageName"}],"floating_images":[],"__type__":"TagConf"},"prebuild_results":{"check_and_set_platforms":["x86_64"]},"buildstep_result":{},"postbuild_results":{},"prepub_results":{},"exit_results":{},"plugin_workspace":{},"plugins_timestamps":{},"plugins_durations":{},"plugins_errors":{},"build_canceled":false,"plugin_failed":false,"reserved_build_id":null,"reserved_token":null,"koji_source_nvr":{},"koji_source_source_url":null,"koji_source_manifest":{},"buildargs":{},"exported_image_sequence":[],"files":{},"image_components":null,"all_yum_repourls":[],"annotations":{},"labels":{},"image_id":null,"parent_images_digests":{}}
```
</details>

<details>
<summary>run (for example in the container used for running unit tests)</summary>

```shell
python3 -m atomic_reactor.cli.main -v task --build-dir /tmp/build --context-dir /tmp/context --user-params-file /tmp/user_params.json --config-file /tmp/config.yaml binary-container-build --platform x86_64
```
</details>

**Review by tkdchen — APPROVED** [review]
Nice!

**Comment by chmeliik** [comment]
Rebased on master and resolved conflict

**Comment by chmeliik** [comment]
Fixed a few potential issues that the `build_imagebuilder` implementation doesn't have: 
* the subprocess polling loop could miss some output because I was checking `poll()` before calling `readline()`
* no longer returning the empty line `''` that `readline()` returns after the process ends

Also added the "last line as error message" that imagebuilder had

**Review by mkosiarc — APPROVED** [review]

**Review by tkdchen — APPROVED** [review]

**Comment by chmeliik** [comment]
No release notes, this doesn't really do anything yet

**Pull request merged**
