### PR TITLE
Remote hosts module

### PR DESCRIPTION
**Pull request by MartinBasti**
# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- n/a JSON/YAML configuration changes are updated in the relevant schema
- n/a Changes to metadata also update the documentation for the metadata
- n/a Pull request has a link to an osbs-docs PR for user documentation updates
- n/a New feature can be disabled from a configuration file

### CODE REVIEW

**Review by qixiang — CHANGES_REQUESTED** [review]
[1] `atomic_reactor/schemas/resource-lock-content.json` is included by accident.
[2] Commit sign-off have two Martin, I believe you were meant to include Adam rather than two of yourself :)

**Comment by MartinBasti** [comment]
> [1] `atomic_reactor/schemas/resource-lock-content.json` is included by accident. [2] Commit sign-off have two Martin, I believe you were meant to include Adam rather than two of yourself :)

[1] removed
[2] removed second myself :D (nope Adam had just backported commit from master)

**Review by qixiang — APPROVED** [review]
:+1:

**Review by chmeliik — APPROVED** [review]

**Comment by chmeliik** [comment]
Waiving documentation and config checklist items, the module itself does not need those

**Pull request merged**
