### PR TITLE
Drop build-host label, log the build host instead

### PR DESCRIPTION
**Pull request by chmeliik**
CLOUDBLD-8832

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- n/a Python type annotations added to new code
- n/a JSON/YAML configuration changes are updated in the relevant schema
- n/a Changes to metadata also update the documentation for the metadata
- n/a Pull request has a link to an osbs-docs PR for user documentation updates
- n/a New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by chmeliik** [comment]
The ticket mentions that we should also log the NVR. I decided not to do that, because properly figuring out the NVR requires inspecting the base image and that seems like too much effort for a single log message. Knowing the pullspec should be good enough, we can get the NVR with e.g. skopeo:
```bash
skopeo inspect --config docker://$pullspec |
    jq '.config.Labels | .["com.redhat.component"] as $name | "\($name)-\(.version)-\(.release)"'
```

**Review by rcerven — APPROVED** [review]

**Review by hjmodi — APPROVED** [review]

**Comment by chmeliik** [comment]
docs PR: https://github.com/containerbuildsystem/osbs-docs/pull/212

**Comment by chmeliik** [comment]
So, I just found out that not setting the label doesn't mean it will not be in the final image - if the parent image was built on OSBS 1 and therefore has the build-host label, then the child image will inherit it :disappointed: 

Best we can do is probably set the label to an empty value

**Review by ben-alkov — APPROVED** [review]

**Comment by chmeliik** [comment]
> So, I just found out that not setting the label doesn't mean it will not be in the final image - if the parent image was built on OSBS 1 and therefore has the build-host label, then the child image will inherit it disappointed
> 
> Best we can do is probably set the label to an empty value

(this would need to be done explicitly, TBD)

**Comment by chmeliik** [comment]
It was decided that since the problem should be only temporary (until all base images are rebuilt on OSBS 2), we should go ahead with this change

Merging

**Comment by chmeliik** [comment]
Added to release notes (Incompatible Changes section):
> - OSBS no longer provides the `com.redhat.build-host` label
>   - However, if the base image has this label, the child will inherit it and it will be incorrect
>   - This is a temporary problem until base images are rebuilt on OSBS 2

**Pull request merged**
