### PR TITLE
Run Bandit static analyzer on CI jobs

### PR DESCRIPTION
**Pull request by athos-ribeiro**
* OSBS-7453

Signed-off-by: Athos Ribeiro <athos@redhat.com>

Maintainers will complete the following section:
- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [x] Pull request includes link to an osbs-docs PR for user documentation updates
- [x] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
Static analysis tools need to be tuned. for now, let's use the same parameters as bandit upstream uses, ignoring warnings with low severity or low confidence.

**Comment by mlangsdorf** [comment]
What's the process for tuning them?  Do we have a document describing the process?

**Comment by athos-ribeiro** [comment]
No RN notes added. CI related change.

**Comment by athos-ribeiro** [comment]
@mlangsdorf, there are only 2 parameters there: severity (-l) and confidence (-i).

We can also ignore specific errors or have a static baseline file. Here are the docs: https://bandit.readthedocs.io/en/latest/config.html

For now, we are just configuring it as bandit upstream does: ignoring low severity or low confidence warnings. Otherwise, the tool would be quite verbose. For instance, it would throw warnings for every import on the subprocess module and whenever the 'key' string is defining a variable.

**Pull request merged**
