### PR TITLE
don't suppress the 'koji' plugin for module-only-composes

### PR DESCRIPTION
**Pull request by owtaylor**
If resolve_composes was run to only compose modules, it would
still suppress the 'koji' plugin which handles adding the koji target
build tag repo to container builds. But modules assume that there's a base
package set coming from somewhere else. So, if we have a compose that only
involves modules, with no packages, pulp repos, inherited repourls, or
user-specified repourls, set the new force_tag_repo(*) parameter on the
client builds, to avoid suppressing the 'koji' plugin.

(*) https://github.com/containerbuildsystem/osbs-client/pull/956

Signed-off-by: Owen W. Taylor <otaylor@fishsoup.net>

Maintainers will complete the following section:
- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [x] Code coverage from testing does not decrease and new code is covered
- [ ] JSON/YAML configuration changes are updated in the relevant schema
- [ ] Changes to metadata also update the documentation for the metadata
- [ ] Pull request includes link to an osbs-docs PR for user documentation updates
- [ ] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by MartinBasti** [comment]
So far LGTM, please address CI errors

**Comment by rcerven** [comment]
LGTM, but tests need fixing

**Comment by owtaylor** [comment]
> No action is needed for the the failing tests (see [containerbuildsystem/osbs-client#957](https://github.com/containerbuildsystem/osbs-client/pull/957)). They should pass when the fixes for the linter warnings are pushed

Thanks! - was scratching my head how my changes could have anything to do with that failure.

**Comment by MartinBasti** [comment]
Stickler linter errors seems unrelated to osbs-client, right?

**Comment by MartinBasti** [comment]
Release notes:
> * don't skip `koji` plugin when no repos are defined/inherited for flatpak builds to work with modules which assume that there is a package set coming from somewhere else

**Pull request merged**
