### PR TITLE
Add unit test for commented out yaml file

### PR DESCRIPTION
**Pull request by lcarva**
This unit test is added to prevent this use case from breaking in the
future.

* CLOUDBLD-76

Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [ ] Pull request has a link to an osbs-docs PR for user documentation updates
- [x] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
For some reason, I cannot re-trigger travis builds anymore

**Comment by lcarva** [comment]
Not updating release notes draft because this is a change solely to unit tests.

**Pull request merged**
