### PR TITLE
Update the check_user_settings plugin for OSBS 2

### PR DESCRIPTION
**Pull request by chmeliik**
- Parse Dockerfile from build dirs, not source dir
- Update util methods the plugin uses to parse the Dockerfile to do the same as ^
- Move the plugin after check_and_set_platforms to make the changes work
- Update other plugins (mostly their unit tests) affected by the util method changes

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [n/a] JSON/YAML configuration changes are updated in the relevant schema
- [n/a] Changes to metadata also update the documentation for the metadata
- [n/a] Pull request has a link to an osbs-docs PR for user documentation updates
- [n/a] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by MartinBasti** [comment]
> PTAL.
> 
> Note that none of the changes are strictly speaking necessary, the changed plugins _could_ keep parsing the original Dockerfile from the source dir instead of the modified one in the build dir. But I don't like that idea, if some parts of the code use the original Dockerfile and others use the modified one, that sounds like a recipe for confusion and hidden bugs.
> 
> But the fact that check_user_settings now has to be _third_ plugin is also a little horrifying (cc @MartinBasti). In my mind, it's still better than mixing which Dockerfile we work with, but I'm open to suggestions.

But `check_user_settings` is supposed to check user input, it should really run before OSBS do any changes there (except cloning). IMO it should just check source at that stage.

**Comment by rcerven** [comment]
> > PTAL.
> > Note that none of the changes are strictly speaking necessary, the changed plugins _could_ keep parsing the original Dockerfile from the source dir instead of the modified one in the build dir. But I don't like that idea, if some parts of the code use the original Dockerfile and others use the modified one, that sounds like a recipe for confusion and hidden bugs.
> > But the fact that check_user_settings now has to be _third_ plugin is also a little horrifying (cc @MartinBasti). In my mind, it's still better than mixing which Dockerfile we work with, but I'm open to suggestions.
> 
> But `check_user_settings` is supposed to check user input, it should really run before OSBS do any changes there (except cloning). IMO it should just check source at that stage.

you could also use just Dockerfile from rootbuilddir instead of platform one

**Comment by chmeliik** [comment]
> But `check_user_settings` is supposed to check user input, it should really run before OSBS do any changes there (except cloning). IMO it should just check source at that stage.

It does run before OSBS does any changes. The rhpkg sources plugin should be considered part of the cloning process (well, at least that's the only way I can justify running it before check_and_set_platforms). And I've expressed many times what I think about the check_and_set_platforms plugin. It's not a plugin, it's an integral step of initializing a pre|post|exit task.

I'll think about letting the check_user_settings check the source Dockerfile instead, but it will require some refactoring and possibly changes to 3 more plugins to pay for the sins of the `has_operator_*_manifest` methods

**Comment by MartinBasti** [comment]
Okay, stay with less painful change for now

**Comment by rcerven** [comment]
> Okay, stay with less painful change for now

alright

**Review by rcerven — APPROVED** [review]

**Review by mkosiarc — APPROVED** [review]

**Comment by mkosiarc** [comment]
LGTM

**Comment by chmeliik** [comment]
RN updated:
- Checking user settings now happens a bit later in the process. Generally, this should make no difference

**Pull request merged**
