### PR TITLE
Move multiple util modules into utils/

### PR DESCRIPTION
**Pull request by SalatskySal**
*OSBS-8605

Also change files which import cachito_util.py

Signed-off-by: Salatskyi Serhii <ssalatsk@redhat.com>

Maintainers will complete the following section:
- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [x] Pull request includes link to an osbs-docs PR for user documentation updates
- [x] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by MartinBasti** [comment]
`No name 'utils' in module 'atomic_reactor'` missing `__init__.py` ?

**Comment by athos-ribeiro** [comment]
Should the `atomic_reactor.util` module be moved into the new package as well?

**Comment by MartinBasti** [comment]
> Should the `atomic_reactor.util` module be moved into the new package as well?

It can be `util.common` but I'd add this in another PR. IMHO this PR has enough changes, I want to merge this fluently.

**Comment by MartinBasti** [comment]
You have inconsistent usrname and email in commits

`Signed-off-by: SalatskySal <sergsalatsky1703@gmail.com>`

**Comment by MartinBasti** [comment]
Looks good otherwise

**Pull request merged**
