### PR TITLE
Allow RegistrySession to use local config file

### PR DESCRIPTION
**Pull request by lcarva**
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

Maintainers will complete the following section:
- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [x] Pull request includes link to an osbs-docs PR for user documentation updates
- [x] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by lcarva** [comment]
Hmm odd, not sure what caused the flatpk tests to fail.

**Comment by athos-ribeiro** [comment]
It seems the latest flatpak/libmodulemd/flatpak-module-tools/fm-orchestrator updates reached the Fedora updates repositories (rebasing will not fix it).

**Comment by owtaylor** [comment]
> It seems the latest flatpak/libmodulemd/flatpak-module-tools/fm-orchestrator updates reached the Fedora updates repositories (rebasing will not fix it).

The failures here are actually from an upstream PyPNG change - it didn't used to verify the length of the row data, and now it does. I have a patch to fix that that is part of a patchset that I was planning to post once https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-90644f2d19 hits stable (tonight). Can split it out, but probably not necessary at this point.

**Comment by athos-ribeiro** [comment]
`master` should be fixed now. Thanks Owen!

**Comment by twaugh** [comment]
@lcarva could you please re-base it again?

**Comment by lcarva** [comment]
> @lcarva could you please re-base it again?

Done! It seems to be passing now.

**Comment by athos-ribeiro** [comment]
Thanks!

Waving documentation and new feature toggle checks.

Release notes added:

- RegistrySession now accepts file paths as well, i.e., one can provide local config files instead of paths for `.dockercfg` or `.dockerconfigjson` files.

**Pull request merged**
