### PR TITLE
Reuse koji_cli.lib.unique_path

### PR DESCRIPTION
**Pull request by tkdchen**
Signed-off-by: Chenxiong Qi <cqi@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [ ] Pull request has a link to an osbs-docs PR for user documentation updates
- [ ] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by tkdchen** [comment]
I'll create a JIRA story for this change.

**Comment by tkdchen** [comment]
A JIRA issue is created and linked in the commit message.

**Comment by MartinBasti** [comment]
No release notes, internal change only

**Pull request merged**
