### PR TITLE
Change the tests for correct working with updated read_yaml method

### PR DESCRIPTION
**Pull request by SalatskySal**
*CLOUDBLD-109

Signed-off-by: Salatskyi Serhii <ssalatsk@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [x] Pull request has a link to an osbs-docs PR for user documentation updates
- [x] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by SalatskySal** [comment]
This PR is related to PR from osbs-client: https://github.com/containerbuildsystem/osbs-client/pull/976. Before reviewing this, we must review and merge PR from osbs-client

**Comment by MartinBasti** [comment]
Works fine in OSBS box

**Comment by MartinBasti** [comment]
no release notes needed, internal change only

**Pull request merged**
