### PR TITLE
koji_parent waits for build in building state to finish

### PR DESCRIPTION
**Pull request by rcerven**
* OSBS-8053

Signed-off-by: Robert Cerven <rcerven@redhat.com>

Maintainers will complete the following section:
- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [x] Pull request includes link to an osbs-docs PR for user documentation updates
- [x] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
Looks good!

Should this behavior only be active if the reserve build feature is enabled as well?

Also, do we need any documentation change?

PS: No idea why coveralls is misbehaving here

**Comment by twaugh** [comment]
Going to waive the code coverage point because all the new code is covered.

**Comment by twaugh** [comment]
@rcerven Was there another race condition you were concerned about?

**Comment by rcerven** [comment]
> @rcerven Was there another race condition you were concerned about?

after thinking, no :)

**Comment by rcerven** [comment]
> Should this behavior only be active if the reserve build feature is enabled as well?
IF reserve build feature is disabled there won't be build in 'building'

**Comment by twaugh** [comment]
No docs needed as far as I can see.

**Comment by rcerven** [comment]
rn updated: koji_parent waits for build in building state to finish

**Pull request merged**
