### PR TITLE
Allow specifying PyPI index mirror

### PR DESCRIPTION
**Pull request by tkdchen**
Signed-off-by: Chenxiong Qi <cqi@redhat.com>

# Maintainers will complete the following section

- [ ] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Changes to metadata also update the documentation for the metadata
- [ ] Pull request has a link to an osbs-docs PR for user documentation updates
- [x] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
LGTM. If we are going for this, would you mind propagating the change to the other repositories under this project?

**Comment by ben-alkov** [comment]
> LGTM. If we are going for this, would you mind propagating the change to the other repositories under this project?

@tkdchen PTAL @ containerbuildsystem/osbs-client#984 before proceeding with this

**Comment by ben-alkov** [comment]
@tkdchen; What is this for? i.e., what is the practical reason for this PR?

**Comment by tkdchen** [comment]
@ben-alkov This is useful for me to choose a PyPI mirror to boost the container environment provision. PyPI is usually too slow for me.

**Comment by chmeliik** [comment]
Release notes not needed, enhancement for local testing only

**Pull request merged**
