### PR TITLE
Use DockerBuildWorkflow fixture in unittests

### PR DESCRIPTION
**Pull request by chmeliik**
* CLOUDBLD-73

Replace most occurrences of DockerBuildWorkflow in unittests with the
existing `workflow` fixture.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

# Maintainers will complete the following section

- [ ] Commit messages are descriptive enough
- [ ] Code coverage from testing does not decrease and new code is covered
- [ ] JSON/YAML configuration changes are updated in the relevant schema
- [ ] Changes to metadata also update the documentation for the metadata
- [ ] Pull request has a link to an osbs-docs PR for user documentation updates
- [ ] New feature can be disabled from a configuration file

### CODE REVIEW

**Comment by chmeliik** [comment]
This is just the result of a fairly mechanical process:
- remove `DockerBuildWorkflow` occurrences in tests
- add `workflow` params to test methods
- if test uses a method to mock the workflow (most of them do), also pass `workflow` to this method
- reindent for 100 character line length limit

Next step could be to try and identify a common subset of workflow setup that is done in most tests and enhance the fixture to do that. Unfortunately, I'm afraid finding that subset would be quite difficult and would require significant refactoring in some tests. Also, setting up more than the bare minimum in the fixture would make it hard to guarantee that some tests do not pass by accident. Not sure if that is worth it.

Speaking of "not worth it", given how much mocking most tests need to do with the workflow, not sure if this is worth it at all.

**Comment by chmeliik** [comment]
@MartinBasti PTAL if this is what you had in mind with CLOUDBLD-73

**Comment by MartinBasti** [comment]
Yes I wanted this. I hoped that this may reduce more duplications.

I imagine that this workflow should provide functional workflow object with dockerfile path, stub inside builder, if MOCK: mock_builder() section. Using tmpdir fixture for dockerfile path shouldn't force us to change many tests.

This fixture can be base fixture for other more specific workflow fixtures.

But if there is not a huge overlap then it may not be worth fixing indeed. I'll take another look to try find clusters. Keep in mind that some tests have just copy pasted mock functions. I wanted to avoid this copy pasting in future by introducing fixtures with sane defaults.

**Comment by MartinBasti** [comment]
I think that this can be used as very basic fixture. It should be easy for tests to update attributes for their needs.
```
workflow = DockerBuildWorkflow(....)
workflow.source = StubSource()
workflow.builder = StubInsideBuilder().for_workflow(workflow)
return workflow
```

**Comment by lcarva** [comment]
It might be more efficient if we only target a single test file to begin with.

**Comment by chmeliik** [comment]
Closing in favor of a nicer solution

**Pull request closed without merging**
